language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7.2

install:
    - travis_retry composer self-update
    - travis_retry composer update
    - travis_retry composer require php-coveralls/php-coveralls

script:
    - composer test-coverage
    - composer cs-check
    - composer analyze

after_script:
    - vendor/bin/php-coveralls -v
