language: php

php:
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer update

script:
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    - vendor/bin/phpcs --standard=PSR2 src tests

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
